export const ADD_RECORD_STARTED = 'ADD_RECORD_STARTED'
export const ADD_RECORD_SECCEEDED = 'ADD_RECORD_SECCEEDED'
export const ADD_RECORD_FAILED = 'ADD_RECORD_FAILED'

export const GET_RECORDS_STARTED = 'GET_RECORDS_STARTED'
export const GET_RECORDS_SUCCEEDED = 'GET_RECORDS_SUCCEEDED'
export const GET_RECORDS_FAILED = 'GET_RECORDS_FAILED'

export const GET_USER_STARTED = 'GET_USER_STARTED'
export const GET_USER_SUCCEEDED = 'GET_USER_SUCCEEDED'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'
